"""State definitions for Astera research pipeline."""

from typing import TypedDict


class ResearchState(TypedDict):
    """Typed representation of the research pipeline execution state.

    Attributes:
        topic: The initial research topic provided by the user.
        search_results: Formatted search engine results from the search agent.
        scraped_content: Extracted web page text content from the reader agent.
        report: Drafted research report generated by the writer chain.
        feedback: Strict evaluation and feedback produced by the critic chain.
    """
    topic: str
    search_results: str
    scraped_content: str
    report: str
    feedback: str
